### ISSUE TITLE
Unable to import SQLite in Python

### ISSUE THREAD

**Issue by JamesHaskell** [disarticulate/docker-python-sqlite#2]
I'm still receiving the same error as before when trying to import SQLite in Python:

```
docker run -it --rm prolocutor/docker-python-sqlite:3.12 /bin/sh 
/ # python
Python 3.5.1 (default, May 25 2016, 02:01:28)
[GCC 5.3.0] on linux
Type "help", "copyright", "credits" or "license" for more information.

import sqlite3
Traceback (most recent call last):
File "", line 1, in 
File "/usr/local/lib/python3.5/sqlite3/init.py", line 23, in 
from sqlite3.dbapi2 import *
File "/usr/local/lib/python3.5/sqlite3/dbapi2.py", line 27, in 
from _sqlite3 import *
ImportError: No module named '_sqlite3'
```

**Comment by disarticulate** [comment]
Looks like I have docker hub set to automated build, and forget to update the 3.12 folder's dockerfile.

Fixed 45ef9c1
